### ISSUE TITLE
Launching an async coroutine with the dispatcher hangs the server permanently.

### ISSUE THREAD

**Issue by ghost** [rocoty/bukkit-scheduler-extensions-kt#16]
If I do
```kotlin
println(Thread.currentThread().name)
runBlocking {
    withContext(dispatcher(plugin, async)) { // hangs here
        println(Thread.currentThread().name)
    }
}
println(Thread.currentThread().name)
```
then the server hangs forever once the async dispatcher is started. Do you have any idea why this might happen?

**Comment by okkero** [comment]
I believe this is because you use `runBlocking`.

**Comment by ghost** [comment]
What coroutine scope do I use? GlobalScope is not recommended since they are never destroyed.

**Comment by okkero** [comment]
Hmm, I guess you could create one scoped to your plugin's lifetime. I might include something that makes this easier in the future, but for now, how about this:

```kt
class Main : JavaPlugin(), CoroutineScope {

    private lateinit var job: Job

    override val coroutineContext: CoroutineContext
        get() = dispatcher() + job

    override fun onEnable() {
        job = Job()
        ...
    }

    override fun onDisable() {
        job.cancel()
        ...
    }

}
```

**Comment by ghost** [comment]
That's super helpful, I'll give it a try. Thank you!

**Comment by okkero** [comment]
Great. I'll close this issue then.
