### ISSUE TITLE
Repeating Task not working

### ISSUE THREAD

**Issue by Jaimss** [rocoty/bukkit-scheduler-extensions-kt#21]
The title may be a bit misleading, it may in fact be working an I am just misunderstanding how to use `repeating`.

### Info
- Skedule Version `1.2.6`
- Kotlin Version `1.4.21`

### Expected Behavior
Start a repeating task that waits 60 seconds, then runs every 60 seconds calling the two methods
- `saveAllData(playerDataCache)`
- `"&aSaved Cache".log()`

### Actual Behavior
A task starts, waits 60 seconds, runs the two methods then stops repeating.

### My Code
```kt
    override val updateTask: CoroutineTask = plugin.server.scheduler.schedule(plugin, SynchronizationContext.ASYNC) {
        waitFor(20 * 60)
        repeating(20 * 60)
        saveAllData(playerDataCache)
        "&aSaved Cache".log()
    }
```

### What I have tried
- Adding a `yield()` after the last `log`.
- Removing the `waitFor`
- Copying the countdown example from the Readme (which worked fine)

### Steps to Reproduce
- Make a minecraft plugin
- Inside `onEnable`, start the above task.
- Cancel it in the `onDisable`

The last step is probably unnecessary but that is the only time I ever do anything relating to the `updateTask` variable.

Please advise, Thanks!

**Comment by JanTuck** [comment]
Having the same issue, I sortof made it work somewhat, quite ugly.


```kotlin
plugin.server.scheduler.schedule(plugin, SynchronizationContext.ASYNC) {
    do {
        waitFor(20 * 60)
        repeating(20 * 60)
        saveAllData(playerDataCache)
        "&aSaved Cache".log()
        yield()
    } while (true)
}
```

**Comment by okkero** [comment]
@JanTuck Yeah, that's how you'd do it. `repeating` does spawn a repeating task, but you have to drive it using `yield` (or some other means of suspending the function). To call yield is essentially to wait for the next iteration of the repeating task before continuing.

Honestly, I think that particular API was a mistake, as it's just awkward to use. Defaulting to use the [CoroutineDispatcher](https://github.com/okkero/Skedule#coroutinedispatcher) approach is probably a good idea, and is likely to be more intuitive in general. Plus it'll be consistent with most other async Kotlin code that way. If I were more active in maintaining this library, that's probably the part I'd focus the most on.

**Comment by okkero** [comment]
To be clear, the idea with `repeating` is to be able to create an async flow without having the library reschedule tasks at every suspension point. In hindsight it's a premature optimisation unlikely to be of much use.

Things like the example in the OP, where you're just doing one thing on a repeating timer, isn't something Skedule is gonna simplify much, if at all, and it's probably a better idea just to use regular Bukkit task scheduling in those situations. Skedule is more useful with more complex async flows where you want to do something, wait for a while, do something else, etc.

**Comment by Jaimss** [comment]
That makes sense. Appreciate the responses!
