### ISSUE TITLE
Maven can not download dependency

### ISSUE THREAD

**Issue by WcaleNieWolny** [rocoty/bukkit-scheduler-extensions-kt#22]
I can not download the dependency. After triedto ping `http://nexus.okkero.com/` i have discovered that your repo is offline.

**Comment by okkero** [comment]
I stopped paying for the server it was served from. I guess I could upload it to some public repo

**Comment by WcaleNieWolny** [comment]
Yeah, that woudl be nice ;)

**Comment by Bloeckchengrafik** [comment]
@WcaleNieWolny If still needed, you can get it via the Mine in Abyss repos at https://repo.mineinabyss.com/#/releases/com/okkero/skedule/1.2.8
