### ISSUE TITLE
Incorrectly using variable for running task on threads

### ISSUE THREAD

**Issue by LoonyRules** [rocoty/bukkit-scheduler-extensions-kt#4]
You may wanna read [this](https://github.com/okkero/Skedule/blob/master/src/main/kotlin/com/okkero/skedule/BukkitDispatcher.kt#L22-L26) again; and it's not the only place you do it either.

If you don't know what I'm referring to then maybe this will help.

`if async, run on sync thread else run on async thread`

That's not what the variable's name is telling the user so you should flip it around.

**Comment by okkero** [comment]
Oh! What a stupid mistake. Thank you for reporting this!
