### ISSUE TITLE
Error when trying to schedule a task

### ISSUE THREAD

**Issue by Redrield** [rocoty/bukkit-scheduler-extensions-kt#6]
Trace: https://hastebin.com/xubufixiza.md

Relevant line: pl.sever.scheduler.schedule(pl, SynchronizationContext.ASYNC) { } (pl is my plugin instance

**Comment by okkero** [comment]
Skedule requires that you have kotlinx.coroutines available in the classpath at runtime. I suppose I should have mentioned that in the readme as well

**Comment by Redrield** [comment]
coroutines is in the classpath. I use coroutines in the enable method to create my database

**Comment by okkero** [comment]
I'm on vacation without a laptop right now, so until I get home on sunday there is not really much I can do.

It does sound a bit strange, however. Because I run Skedule without a problem, having both the kotlin 1.1 stdlib and kotlinx.coroutines somewhere in the classpath as the server is running.

**Comment by Redrield** [comment]
I've narrowed the issue down. Something available in kotlinx.coroutines 0.12 that you utilize was removed in future versions, thus the NoSuchMethodError. Until a fix is available I've found that syncing my version of coroutines with that in the project has solved it

**Comment by okkero** [comment]
Okay. Sorry for the inconvenience, and thank you for helping me debug that. I will see to fixing it ASAP when I get home

**Comment by okkero** [comment]
Should be good now.
https://github.com/okkero/Skedule/releases/tag/v1.2.2
